In [ ]:
# Numpy 기본

# 차원 미니퀘스트 1번
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim)

# 차원 미니퀘스트 2번
array = np.array([10, 20, 30, 40, 50, 60])

print(array.reshape(2,3))

# 차원 미니퀘스트 3번
array = np.array([7, 14, 21])

column_vector = array[:, np.newaxis]
row_vector = array[np.newaxis, :]

print("column_vector:\n", column_vector)
print("column_vector.ndim:\n", column_vector.ndim)

print("row_vector:\n", row_vector)
print("row_vector.nid:\n", row_vector.ndim)

In [ ]:

# Shape 미니퀘스트 1번
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

# Shape 미니퀘스트 2번
array = np.array([10, 20, 30, 40, 50, 60])
reshape_array = array.reshape(2,3)

print(reshape_array)

# Shape 미니퀘스트 3번
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshape_array = array.reshape(3,2,2)

print(reshape_array)

(2, 3)
[[10 20 30]
 [40 50 60]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:

# 데이터 타입 미니퀘스트 1번
array = np.array([10, 20, 30])

print(array.dtype)

# 데이터 타입 미니퀘스트 2번
array = np.array([1, 2, 3], dtype=np.int16)
converted_array = array.astype(np.float16)

print(converted_array.dtype)

# 데이터 타입 미니퀘스트 3번
array = np.array([100, 200, 300], dtype=np.int64)
converted_array = array.astype(np.str_)

print(converted_array.nbytes)

int64
float16
252


In [ ]:

# 인덱싱 미니퀘스트 1번
array = np.array([10, 20, 30, 40, 50])

print(array[0], array[-1])

# 인덱싱 미니퀘스트 2번
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[:,0], matrix[1,:])

# 인덱싱 미니퀘스트 3번
array = np.array([5, 15, 8, 20, 3, 12])

result = []
filtered = array[array > 10]

for i in range(len(array)):
  if array[i] in filtered :
    result.append(i)

print(result)

10 50
[1 4 7] [4 5 6]
[1, 3, 5]


In [ ]:

# 연산 미니퀘스트 1번

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)

# 연산 미니퀘스트 2번

matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])

print(matrix + vector)

# 연산 미니퀘스트 3번

array = np.array([[3, 7, 2], [8, 4, 6]])

axis0_array = np.max(array, axis=0)
axis1_array = np.max(array, axis=1)

print(axis0_array, axis0_array.ndim)
print(axis1_array, axis1_array.ndim)



[5 7 9]
[[11 22 33]
 [41 52 63]]
[8 7 6] 1
[7 8] 1


In [ ]:
# 유니버셜 함수 미니퀘스트 1번

array = np.array([1, 2, 3, 4])

print(np.power(array, 2))

# 유니버셜 함수 미니퀘스트 2번

array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])

np.add(array1, array2, out=array1)

print(array1)

# 유니버셜 함수 미니퀘스트 3번

array = np.array([1, np.e, 10, 100])

np.log(array, out=array)

result = []

for i in range(len(array)):
  if array[i] > 1:
    result.append(array[i])

print(result)

[ 1  4  9 16]
[11 22 33]
[np.float64(2.302585092994046), np.float64(4.605170185988092)]
